import type { Icon } from "@phosphor-icons/react";
import {
  AndroidLogo,
  AppleLogo,
  Article,
  Atom,
  Bird,
  BookOpenText,
  Blueprint,
  Brain,
  Briefcase,
  Browser,
  Buildings,
  Calculator,
  ChartLineUp,
  ChartPie,
  ChalkboardTeacher,
  ChefHat,
  Cloud,
  Code,
  Coffee,
  Cpu,
  CurrencyDollar,
  Database,
  FilmStrip,
  FilePy,
  FirstAid,
  Flask,
  GearSix,
  Gavel,
  Globe,
  Handshake,
  Headset,
  ImageSquare,
  Kanban,
  Layout,
  LinkSimple,
  ListChecks,
  Lock,
  MagnifyingGlass,
  Megaphone,
  Microscope,
  OfficeChair,
  PaintBrush,
  Pen,
  Pill,
  PlugsConnected,
  PresentationChart,
  Pulse,
  Question,
  Ruler,
  ShareNetwork,
  ShieldCheck,
  Stack,
  Star,
  Stethoscope,
  Tree,
  TrendUp,
  UsersThree,
  Bug,
  Wrench,
} from "@phosphor-icons/react";

/** Phosphor icons aligned to each role title (Figma 2338:55152 — 16px regular weight). */
export const ROLE_ICONS: Record<string, Icon> = {
  Accountant: Calculator,
  "Android Developer": AndroidLogo,
  Attorney: Gavel,
  "Backend Developer": Cpu,
  "Business Analyst": PresentationChart,
  Chef: ChefHat,
  "Cloud Architect": Cloud,
  "Content Strategist": Article,
  Copywriter: Pen,
  "Customer Success Manager": Handshake,
  "Cyber Security Analyst": ShieldCheck,
  "Data Analyst": ChartLineUp,
  "Data Scientist": Flask,
  "Database Administrator": Database,
  Designer: PaintBrush,
  "DevOps Engineer": GearSix,
  "Financial Analyst": CurrencyDollar,
  "Frontend Developer": Browser,
  "Full Stack Developer": Stack,
  "Graphic Designer": ImageSquare,
  "HR Manager": UsersThree,
  "IT Support Specialist": Wrench,
  "iOS Developer": AppleLogo,
  "Machine Learning Engineer": Brain,
  "Marketing Manager": Megaphone,
  "Nurse Practitioner": Stethoscope,
  "Operations Manager": Buildings,
  Pharmacist: Pill,
  "Physician Assistant": FirstAid,
  "Product Analyst": ChartPie,
  "Product Designer": Ruler,
  "Product Manager": Briefcase,
  "Project Manager": Kanban,
  "Python Developer": FilePy,
  "QA Engineer": Bug,
  "Sales Representative": TrendUp,
  Scientist: Microscope,
  "Scrum Master": ListChecks,
  "Social Media Manager": ShareNetwork,
  "Software Engineer": Code,
  Teacher: ChalkboardTeacher,
  "Technical Writer": BookOpenText,
  "UX Designer": Layout,
  "UX Researcher": MagnifyingGlass,
  "Video Editor": FilmStrip,
  "Web Developer": Globe,
  "Blockchain Developer": LinkSimple,
  "Data Engineer": PlugsConnected,
  "Engineering Manager": OfficeChair,
  "Kotlin Developer": Coffee,
  "Node.js Developer": Tree,
  "React Developer": Atom,
  "Rust Developer": GearSix,
  "Security Engineer": Lock,
  "Site Reliability Engineer": Pulse,
  "Solutions Architect": Blueprint,
  "Swift Developer": Bird,
  "Tech Lead": Star,
};

export function RoleIcon({ title, className }: { title: string; className?: string }) {
  const Cmp = ROLE_ICONS[title] ?? Question;
  return <Cmp size={16} weight="regular" className={className} aria-hidden />;
}
